version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_kinesis
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
      - DEBUG=1
      - LOCALSTACK_TMPDIR=/var/lib/localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
